### ISSUE TITLE
Arquivos compilados

### ISSUE THREAD

**Issue by 8rux40** [leandroviersberg/EstudoDeTeste#2]
### Parabéns pelos estudos, Leandro! 👏🏻👏🏻

Uma dica que te dou é incluir na pasta raiz do projeto um arquivo chamado **.gitignore**.
Não sei se já usou alguma vez, mas caso não conheça, é um arquivo que informa para o Git **quais partes do seu repositório devem ser ignoradas** e não versionadas. Acredito que a pasta [EstudoDeTeste/AutomacodeBank/bin/RegraNegocio/](https://github.com/leandroviersberg/EstudoDeTeste/tree/Estudos/AutomacodeBank/bin/RegraNegocio) deve ser omitida para o Git.

**Comment by leandroviersberg** [comment]
Muito obrigado pelas dicas , ainda como estou iniciando tenho muito que
aprender com vcs!!
Vlw pela dica
*Att,*

*Leandro Viersberg*


Em ter., 18 de mai. de 2021 às 13:42, Bruno Tardin ***@***.***>
escreveu:
